// <auto-generated />
using EpitmenyadoWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EpitmenyadoWebApp.Migrations
{
    [DbContext(typeof(EpitmenyDbContext))]
    [Migration("20240930081157_sqlite.local_migration_157")]
    partial class sqlitelocal_migration_157
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("EpitmenyadoWebApp.Models.Telkek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdoSzam")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlapTerulet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HazSzam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<char>("Sav")
                        .HasColumnType("TEXT");

                    b.Property<string>("UtcaNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Telkeks");
                });
#pragma warning restore 612, 618
        }
    }
}
